name: sms_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.1.0
  background_sms: ^0.0.1
  provider: 
  shared_preferences: ^2.2.2
  qr_code_scanner: ^1.0.1
  vibration: ^1.8.4
  url_launcher: ^6.1.4
  http: ^1.1.2
  device_info_plus: ^9.1.1
  timeago: ^3.6.0
  flutter_local_notifications: ^16.3.0
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2


flutter:
  uses-material-design: true

flutter_launcher_icons: 
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  image_path: "assets/icon.png"
  android: true
  ios: true

